import { Metadata } from "next"
import { title } from "process"

export const metadata = {
  title:{
    absolute: "",
    default: "Nextjs tutorial",
    template:"%s | Code evolution" /* Here %s will be replaced by the title given in that particular route and also the pipe 
    sign will be there and the  text after that will be as well. */
  },
  description: 'Generated by Next.js',
}
//Next js automatically creates this file
export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <header
        style={{
          backgroundColor: "lightblue",
          padding: "1rem"
        }}>
          <p>Header</p>
        </header>
        {children}
        <footer  style={ {backgroundColor: "lightblue",
          padding: "1rem"}}>
            <p>Footer</p>
          </footer>
        </body>
    </html>
  )
}
